// Package bootstrap is autowired dependency injection module,
package bootstrap

// Code generated by autowired. DO NOT EDIT.
// Generated from 43 source files

import (
    "go.uber.org/fx"
    account "sapasora/internal/app/http/controllers/account"
    account1 "sapasora/internal/modules/account"
    apikey "sapasora/internal/app/http/controllers/apikey"
    apikey1 "sapasora/internal/modules/apikey"
    auth "sapasora/internal/app/http/controllers/auth"
    config "sapasora/internal/config"
    controllers "sapasora/internal/app/http/controllers"
    dashboard "sapasora/internal/app/http/controllers/dashboard"
    device "sapasora/internal/app/http/controllers/device"
    device1 "sapasora/internal/modules/device"
    devicelifecycle "sapasora/internal/modules/devicelifecycle"
    devicetoken "sapasora/internal/app/http/controllers/devicetoken"
    devicetoken1 "sapasora/internal/modules/devicetoken"
    gateway "sapasora/internal/app/http/controllers/gateway"
    gateway1 "sapasora/internal/modules/gateway"
    middleware "sapasora/internal/app/http/middleware"
    migrations "sapasora/internal/migrations"
    role "sapasora/internal/app/http/controllers/role"
    role1 "sapasora/internal/modules/role"
    routes "sapasora/internal/app/routes"
    telegram "sapasora/internal/modules/telegram"
    whatsapp "sapasora/internal/modules/whatsapp"
)

// Auto-generated from 42 constructors

// AutowiredModule returns fx.Option with all auto-discovered dependencies
var AutowiredModule = fx.Options(
    AutowiredProvidersModule,
    AutowiredDecoratorsModule,
)

// Individual modules for selective inclusion

// AutowiredProvidersModule returns only provider functions
var AutowiredProvidersModule = fx.Options(
    fx.Provide(account.NewAccountController),
    fx.Provide(account1.NewAccountRepository),
    fx.Provide(account1.NewAccountService),
    fx.Provide(apikey.NewAPIKeyController),
    fx.Provide(apikey1.NewAPIKeyRepository),
    fx.Provide(apikey1.NewAPIKeyService),
    fx.Provide(auth.NewAuthController),
    fx.Provide(fx.Annotate(NewSchedules, fx.ResultTags(`group:"schedules"`))),
    fx.Provide(controllers.NewController),
    fx.Provide(controllers.NewWelcomeController),
    fx.Provide(dashboard.NewDashboardController),
    fx.Provide(device.NewDeviceController),
    fx.Provide(device1.NewDeviceRepository),
    fx.Provide(device1.NewDeviceService),
    fx.Provide(devicelifecycle.NewDeviceDeletionService),
    fx.Provide(devicetoken.NewDeviceTokenController),
    fx.Provide(devicetoken1.NewDeviceTokenRepository),
    fx.Provide(devicetoken1.NewDeviceTokenService),
    fx.Provide(gateway.NewGatewayController),
    fx.Provide(gateway1.NewGatewayService),
    fx.Provide(func(service gateway1.GatewayService) devicelifecycle.ProviderDisconnector {
        return service
    }),
    fx.Provide(middleware.NewAuthenticationMiddleware),
    fx.Provide(middleware.NewInertiaMiddleware),
    fx.Provide(fx.Annotate(migrations.NewCreateMApiKeysTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMDeviceTokensTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMDevicesTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMRolesTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMUsersTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(role.NewRoleController),
    fx.Provide(role1.NewRoleRepository),
    fx.Provide(role1.NewRoleService),
    fx.Provide(fx.Annotate(routes.APIRouter, fx.ResultTags(`group:"router"`))),
    fx.Provide(fx.Annotate(routes.ChannelRouter, fx.ResultTags(`group:"router"`))),
    fx.Provide(routes.NewAPI),
    fx.Provide(routes.NewChannel),
    fx.Provide(routes.NewWeb),
    fx.Provide(fx.Annotate(routes.WebRouter, fx.ResultTags(`group:"router"`))),
    fx.Provide(telegram.NewTDLib),
    fx.Provide(telegram.NewTelegramService),
    fx.Provide(whatsapp.NewWhatsappService),
    fx.Provide(whatsapp.NewWhatsmeow),
)

// AutowiredDecoratorsModule returns only decorator functions
var AutowiredDecoratorsModule = fx.Options(
    fx.Decorate(Bundler),
    fx.Decorate(Inertia),
    fx.Decorate(config.NewAppConfig),
)

// Group-specific modules

// MigrationsGroupModule returns dependencies for group "Migrations"
var MigrationsGroupModule = fx.Options(
    fx.Provide(fx.Annotate(migrations.NewCreateMApiKeysTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMDeviceTokensTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMDevicesTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMRolesTable, fx.ResultTags(`group:"migrations"`))),
    fx.Provide(fx.Annotate(migrations.NewCreateMUsersTable, fx.ResultTags(`group:"migrations"`))),
)

// RouterGroupModule returns dependencies for group "Router"
var RouterGroupModule = fx.Options(
    fx.Provide(fx.Annotate(routes.APIRouter, fx.ResultTags(`group:"router"`))),
    fx.Provide(fx.Annotate(routes.ChannelRouter, fx.ResultTags(`group:"router"`))),
    fx.Provide(fx.Annotate(routes.WebRouter, fx.ResultTags(`group:"router"`))),
)

// SchedulesGroupModule returns dependencies for group "Schedules"
var SchedulesGroupModule = fx.Options(
    fx.Provide(fx.Annotate(NewSchedules, fx.ResultTags(`group:"schedules"`))),
)

// Registry information for debugging
var (
    // Providers contains all provider functions
    Providers = []any{
        account.NewAccountController,
        account1.NewAccountRepository,
        account1.NewAccountService,
        apikey.NewAPIKeyController,
        apikey1.NewAPIKeyRepository,
        apikey1.NewAPIKeyService,
        auth.NewAuthController,
        NewSchedules,
        controllers.NewController,
        controllers.NewWelcomeController,
        dashboard.NewDashboardController,
        device.NewDeviceController,
        device1.NewDeviceRepository,
        device1.NewDeviceService,
        devicelifecycle.NewDeviceDeletionService,
        devicetoken.NewDeviceTokenController,
        devicetoken1.NewDeviceTokenRepository,
        devicetoken1.NewDeviceTokenService,
        gateway.NewGatewayController,
        gateway1.NewGatewayService,
        middleware.NewAuthenticationMiddleware,
        middleware.NewInertiaMiddleware,
        migrations.NewCreateMApiKeysTable,
        migrations.NewCreateMDeviceTokensTable,
        migrations.NewCreateMDevicesTable,
        migrations.NewCreateMRolesTable,
        migrations.NewCreateMUsersTable,
        role.NewRoleController,
        role1.NewRoleRepository,
        role1.NewRoleService,
        routes.APIRouter,
        routes.ChannelRouter,
        routes.NewAPI,
        routes.NewChannel,
        routes.NewWeb,
        routes.WebRouter,
        telegram.NewTDLib,
        telegram.NewTelegramService,
        whatsapp.NewWhatsappService,
        whatsapp.NewWhatsmeow,
    }

    // Decorators contains all decorator functions
    Decorators = []any{
        Bundler,
        Inertia,
        config.NewAppConfig,
    }


    // ConstructorInfo provides metadata about each constructor
    ConstructorInfo = map[string]string{
        "account.NewAccountController": "internal/app/http/controllers/account/account.go:provide - NewAccountController creates a new Accountcontrollers",
        "account1.NewAccountRepository": "internal/modules/account/repository.go:provide - NewAccountRepository creates a new Implementation of AccountRepository",
        "account1.NewAccountService": "internal/modules/account/service.go:provide - NewAccountService creates a new Implementation of AccountService",
        "apikey.NewAPIKeyController": "internal/app/http/controllers/apikey/apikey.go:provide - NewAPIKeyController creates a new APIKeycontrollers",
        "apikey1.NewAPIKeyRepository": "internal/modules/apikey/repository.go:provide - NewAPIKeyRepository creates a new Implementation of APIKeyRepository",
        "apikey1.NewAPIKeyService": "internal/modules/apikey/service.go:provide - NewAPIKeyService creates a new Implementation of APIKeyService",
        "auth.NewAuthController": "internal/app/http/controllers/auth/auth.go:provide - NewAuthController creates a new Authcontrollers",
        "Bundler": "internal/app/bootstrap/bundler.go:decorate - Bundler decorates the bundler",
        "Inertia": "internal/app/bootstrap/inertia.go:decorate - Inertia is the middleware for the inertia",
        "NewSchedules": "internal/app/bootstrap/schedules.go:provide - NewSchedules creates a new cron scheduler",
        "config.NewAppConfig": "internal/config/config.go:decorate - NewAppConfig returns a new AppConfig instance",
        "controllers.NewController": "internal/app/http/controllers/controller.go:provide - NewController creates a new controller for the application",
        "controllers.NewWelcomeController": "internal/app/http/controllers/welcome_controller.go:provide - NewWelcomeController creates a new controller for the welcome page",
        "dashboard.NewDashboardController": "internal/app/http/controllers/dashboard/dashboard.go:provide - NewDashboardController creates a new Dashboardcontrollers",
        "device.NewDeviceController": "internal/app/http/controllers/device/device.go:provide - NewDeviceController creates a new Devicecontrollers",
        "device1.NewDeviceRepository": "internal/modules/device/repository.go:provide - NewDeviceRepository creates a new Implementation of DeviceRepository",
        "device1.NewDeviceService": "internal/modules/device/service.go:provide - NewDeviceService creates a new Implementation of DeviceService",
        "devicelifecycle.NewDeviceDeletionService": "internal/modules/devicelifecycle/service.go:provide - NewDeviceDeletionService creates the T0.8 device deletion coordinator",
        "devicetoken.NewDeviceTokenController": "internal/app/http/controllers/devicetoken/devicetoken.go:provide - NewDeviceTokenController creates a new DeviceTokencontrollers",
        "devicetoken1.NewDeviceTokenRepository": "internal/modules/devicetoken/repository.go:provide - NewDeviceTokenRepository creates a new Implementation of DeviceTokenRepository",
        "devicetoken1.NewDeviceTokenService": "internal/modules/devicetoken/service.go:provide - NewDeviceTokenService creates a new Implementation of DeviceTokenService",
        "gateway.NewGatewayController": "internal/app/http/controllers/gateway/gateway.go:provide - NewGatewayController creates a new Gatewaycontrollers",
        "gateway1.NewGatewayService": "internal/modules/gateway/service.go:provide - NewGatewayService creates a new Implementation of GatewayService",
        "middleware.NewAuthenticationMiddleware": "internal/app/http/middleware/authentication.go:provide - NewAuthenticationMiddleware creates a new middleware for the authentication",
        "middleware.NewInertiaMiddleware": "internal/app/http/middleware/inertia.go:provide - NewInertiaMiddleware creates a new middleware for the inertia",
        "migrations.NewCreateMApiKeysTable": "internal/migrations/2025_12_18_210307_create_m_api_keys_table.go:provide - NewCreateMApiKeysTable creates a new CreateMApiKeysTable instance",
        "migrations.NewCreateMDeviceTokensTable": "internal/migrations/2025_12_17_104729_create_m_device_tokens_table.go:provide - NewCreateMDeviceTokensTable creates a new CreateMDeviceTokensTable instance",
        "migrations.NewCreateMDevicesTable": "internal/migrations/2025_12_17_102702_create_m_devices_table.go:provide - NewCreateMDevicesTable creates a new CreateMDevicesTable instance",
        "migrations.NewCreateMRolesTable": "internal/migrations/2025_12_17_102624_create_m_roles_table.go:provide - NewCreateMRolesTable creates a new CreateMRolesTable instance",
        "migrations.NewCreateMUsersTable": "internal/migrations/2025_12_17_102646_create_m_users_table.go:provide - NewCreateMUsersTable creates a new CreateMUsersTable instance",
        "role.NewRoleController": "internal/app/http/controllers/role/role.go:provide - NewRoleController creates a new Rolecontrollers",
        "role1.NewRoleRepository": "internal/modules/role/repository.go:provide - NewRoleRepository creates a new Implementation of RoleRepository",
        "role1.NewRoleService": "internal/modules/role/service.go:provide - NewRoleService creates a new Implementation of RoleService",
        "routes.APIRouter": "internal/app/routes/api.go:provide - APIRouter is the router for the API, usually everything that is just the api and will be consumed by other applications",
        "routes.ChannelRouter": "internal/app/routes/channel.go:provide - ChannelRouter is the router for the WebSocket, usually everything that is not an API or will be consumed by this application only",
        "routes.NewAPI": "internal/app/routes/pipeline.go:provide - NewAPI create a new pipeline for the API",
        "routes.NewChannel": "internal/app/routes/pipeline.go:provide - NewChannel create a new pipeline for the Channel",
        "routes.NewWeb": "internal/app/routes/pipeline.go:provide - NewWeb create a new pipeline for the web",
        "routes.WebRouter": "internal/app/routes/web.go:provide - WebRouter is the router for the web, usually everything that is not an API or will be consumed by this application only",
        "telegram.NewTDLib": "internal/modules/telegram/tdlib.go:provide - NewTDLib creates a new TDLib instance",
        "telegram.NewTelegramService": "internal/modules/telegram/service.go:provide - NewTelegramService creates a new Implementation of TelegramService",
        "whatsapp.NewWhatsappService": "internal/modules/whatsapp/service.go:provide - NewWhatsappService creates a new Implementation of WhatsappService",
        "whatsapp.NewWhatsmeow": "internal/modules/whatsapp/whatsmeow.go:provide - NewWhatsmeow creates a new Whatsmeow instance.",
    }
)